import { afterAll, describe, expect, it } from "bun:test";
import { mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  type ArchitectureSnapshot,
  defaultArchitectureDocPath,
  renderArchitectureDoc,
  writeArchitectureDoc,
} from "../architecture-doc";

const FIXED_TS = "2026-05-26T13:00:00.000Z";

function snapshot(partial: Partial<ArchitectureSnapshot> = {}): ArchitectureSnapshot {
  return {
    pluginVersion: "2.2.99",
    runtime: "bus",
    agents: [],
    jobs: [],
    adapters: [],
    generatedAt: FIXED_TS,
    ...partial,
  };
}

describe("renderArchitectureDoc — determinism + structure", () => {
  it("produces byte-identical output for the same input (determinism)", () => {
    const s = snapshot({
      agents: [{ id: "default", permissionMode: "bypassPermissions" }],
    });
    expect(renderArchitectureDoc(s)).toEqual(renderArchitectureDoc(s));
  });

  it("starts with the do-not-edit banner and version stamp", () => {
    const out = renderArchitectureDoc(snapshot());
    expect(out).toMatch(/^<!--\s*\n\s*CCPLUS_ARCHITECTURE\.md — daemon-generated/);
    expect(out).toContain("Auto-generated by ClaudeClaw+ 2.2.99 at 2026-05-26T13:00:00.000Z");
  });

  it("renders bus-runtime narrative when runtime=bus", () => {
    const out = renderArchitectureDoc(snapshot({ runtime: "bus" }));
    expect(out).toContain("Mode: **`bus`**");
    expect(out).toContain("typed event bus (`BusCore`)");
    expect(out).toContain("JSONL session log");
  });

  it("renders pty-runtime narrative when runtime=pty", () => {
    const out = renderArchitectureDoc(snapshot({ runtime: "pty" }));
    expect(out).toContain("Mode: **`pty`**");
    expect(out).toContain("`claude -p` subprocess");
    expect(out).toContain("Agent SDK credit pool");
  });

  it("warns about empty agents under bus runtime", () => {
    const out = renderArchitectureDoc(snapshot({ runtime: "bus", agents: [] }));
    expect(out).toContain("No agents declared");
    expect(out).toContain("publishes to the bus with no consumer");
  });

  it("does NOT warn about empty agents under pty runtime (irrelevant there)", () => {
    const out = renderArchitectureDoc(snapshot({ runtime: "pty", agents: [] }));
    expect(out).toContain("No agents declared");
    expect(out).not.toContain("publishes to the bus with no consumer");
  });

  it("lists declared agents with their optional fields", () => {
    const out = renderArchitectureDoc(
      snapshot({
        agents: [
          { id: "default", permissionMode: "bypassPermissions" },
          { id: "reg", permissionMode: "plan", cwd: "/srv/reg", systemPromptFile: "/etc/reg.md" },
        ],
      }),
    );
    expect(out).toContain("`default`");
    expect(out).toContain("permission_mode `bypassPermissions`");
    expect(out).toContain("`reg`");
    expect(out).toContain("permission_mode `plan`");
    expect(out).toContain("cwd `/srv/reg`");
    expect(out).toContain("system prompt `/etc/reg.md`");
  });

  it("groups jobs by agent in alphabetical order", () => {
    const out = renderArchitectureDoc(
      snapshot({
        jobs: [
          { agent: "reg", label: "daily-content-research", schedule: "0 5 * * *", enabled: true },
          { agent: "default", label: "morning-check", schedule: "0 8 * * *", enabled: true },
          { agent: "reg", label: "image-generation", schedule: "0 6 * * *", enabled: false },
        ],
      }),
    );
    // Sorted alphabetically — default before reg.
    const defaultIdx = out.indexOf("### `default`");
    const regIdx = out.indexOf("### `reg`");
    expect(defaultIdx).toBeGreaterThan(0);
    expect(regIdx).toBeGreaterThan(defaultIdx);
    expect(out).toContain("`daily-content-research`");
    expect(out).toContain("`0 5 * * *`");
    expect(out).toContain("`image-generation`");
    expect(out).toContain("_disabled_");
  });

  it("lists adapters with optional detail strings", () => {
    const out = renderArchitectureDoc(
      snapshot({
        adapters: [{ name: "discord", detail: "5 channels routed" }, { name: "telegram" }],
      }),
    );
    expect(out).toContain("**discord** — 5 channels routed");
    expect(out).toContain("**telegram**");
  });

  it("always includes the diagnostic playbook section", () => {
    const out = renderArchitectureDoc(snapshot());
    expect(out).toContain("## Diagnostic playbook");
    expect(out).toContain("Check `runtime` in `settings.json`");
    expect(out).toContain("Compare `agents/<name>/` dirs to `settings.agents[]`");
    expect(out).toContain("Do not guess at PTY timeouts");
  });
});

describe("writeArchitectureDoc — atomic write", () => {
  const tmp = mkdtempSync(join(tmpdir(), "ccplus-arch-doc-"));

  afterAll(() => {
    rmSync(tmp, { recursive: true, force: true });
  });

  it("writes the rendered content atomically to the target path", () => {
    const path = join(tmp, "CCPLUS_ARCHITECTURE.md");
    const rendered = writeArchitectureDoc(snapshot({ runtime: "bus" }), path);
    const onDisk = readFileSync(path, "utf8");
    expect(onDisk).toBe(rendered);
    expect(onDisk).toContain("Mode: **`bus`**");
  });

  it("overwrites the file on subsequent calls (re-runs are safe)", () => {
    const path = join(tmp, "CCPLUS_ARCHITECTURE.md");
    writeArchitectureDoc(snapshot({ runtime: "bus" }), path);
    writeArchitectureDoc(snapshot({ runtime: "pty" }), path);
    const onDisk = readFileSync(path, "utf8");
    expect(onDisk).toContain("Mode: **`pty`**");
    expect(onDisk).not.toContain("Mode: **`bus`**");
  });
});

describe("defaultArchitectureDocPath", () => {
  it("returns the conventional project-root path next to CLAUDE.md", () => {
    expect(defaultArchitectureDocPath("/srv/project")).toBe("/srv/project/CCPLUS_ARCHITECTURE.md");
  });
});
