/**
 * Generate `CCPLUS_ARCHITECTURE.md` — a daemon-authored Markdown file that
 * tells the spawned agent which runtime it's on, which agents are
 * declared, which jobs are scheduled, which adapters are mounted, and how
 * to diagnose silent failures.
 *
 * Why this file exists (issue #166): a deployed agent asked to diagnose
 * "why are scheduled jobs not running" produced a confident-but-wrong
 * answer because it had no way to introspect its own runtime — it didn't
 * know whether it was on bus or pty, which agents existed, or how prompts
 * flowed. The architecture doc lives alongside `CLAUDE.md` so the agent
 * reads it as bootstrap context and can diagnose by ground-truth instead
 * of guessing.
 *
 * Design:
 *   - **Daemon-owned, do not edit.** The leading "do not edit" banner is
 *     load-bearing — operators are explicitly told to not commit the
 *     file (`.gitignore` entry) and not hand-edit it. Regenerated on
 *     every daemon startup.
 *   - **Atomic write.** Write-to-temp then rename so a partially-written
 *     file never reaches Claude's context.
 *   - **Pure generator.** `renderArchitectureDoc(snapshot)` is a pure
 *     function — same input, byte-identical output. I/O lives in
 *     `writeArchitectureDoc`.
 */

import { writeFileSync, renameSync, unlinkSync } from "node:fs";
import { join } from "node:path";

/* ───────────────────────────────────────────────────────────────────── */
/* Snapshot types                                                        */
/* ───────────────────────────────────────────────────────────────────── */

export interface ArchitectureSnapshotAgent {
  id: string;
  permissionMode?: string;
  cwd?: string;
  systemPromptFile?: string;
  memoryFile?: string;
}

export interface ArchitectureSnapshotJob {
  agent: string;
  label: string;
  schedule?: string;
  enabled: boolean;
}

export interface ArchitectureSnapshotAdapter {
  name: string;
  /** Free-form note: e.g. "5 channels routed", "1 chat routed". */
  detail?: string;
}

export interface ArchitectureSnapshot {
  pluginVersion: string;
  /** `"bus"` or `"pty"`. Anything else is rendered as-is for forward-compat. */
  runtime: string;
  agents: readonly ArchitectureSnapshotAgent[];
  jobs: readonly ArchitectureSnapshotJob[];
  adapters: readonly ArchitectureSnapshotAdapter[];
  /** ISO timestamp the snapshot was taken. */
  generatedAt: string;
}

/* ───────────────────────────────────────────────────────────────────── */
/* Pure generator                                                        */
/* ───────────────────────────────────────────────────────────────────── */

/**
 * Render the architecture markdown for a given snapshot. Pure — no I/O,
 * no `Date.now()`, no `process.env`. The snapshot's `generatedAt` is the
 * only timestamp the output references, so callers control determinism
 * by controlling the input.
 */
export function renderArchitectureDoc(snapshot: ArchitectureSnapshot): string {
  const lines: string[] = [];

  lines.push("<!--");
  lines.push("  CCPLUS_ARCHITECTURE.md — daemon-generated. Do not edit by hand.");
  lines.push("  Rewritten on every daemon startup. Commit-ignore this file.");
  lines.push("-->");
  lines.push("");
  lines.push("# ClaudeClaw+ — Your Operating Architecture");
  lines.push("");
  lines.push(
    `_Auto-generated by ClaudeClaw+ ${snapshot.pluginVersion} at ${snapshot.generatedAt}._`,
  );
  lines.push("");
  lines.push("You are running on **ClaudeClaw+**. This file is the daemon's");
  lines.push("self-description of your runtime environment. When asked to diagnose");
  lines.push("anything about how jobs / messages / agents flow, **read this first**");
  lines.push("rather than guessing from prior assumptions.");
  lines.push("");

  /* Runtime ────────────────────────────────────────────────────────── */
  lines.push("## Runtime");
  lines.push("");
  if (snapshot.runtime === "bus") {
    lines.push("Mode: **`bus`** (v2.0 default).");
    lines.push("");
    lines.push("- One long-lived `claude` process per agent declared in `settings.agents[]`.");
    lines.push("- Adapters publish inbound events to a typed event bus (`BusCore`).");
    lines.push("- Agents subscribe to their `agent_id`-keyed prompts; replies flow back");
    lines.push("  as `response.text` / `channel.permission_request` / `system.request_human`.");
    lines.push("- Output is read by tailing Claude's own JSONL session log under");
    lines.push("  `~/.claude/projects/<cwd>/<session>.jsonl` — **not** by parsing stdout.");
  } else if (snapshot.runtime === "pty") {
    lines.push("Mode: **`pty`** (legacy `claude -p` subprocess path).");
    lines.push("");
    lines.push("- One `claude -p` subprocess per inbound event (no long-lived processes).");
    lines.push("- API-billed via the Agent SDK credit pool (post-2026-06-15 Anthropic split).");
    lines.push("- Kept as a permanent first-class option for enterprise deployments");
    lines.push("  where audit / cost-ceiling / regulatory constraints make API billing");
    lines.push("  the safer or only viable route.");
  } else {
    lines.push(`Mode: \`${snapshot.runtime}\` (unrecognised — check \`settings.runtime\`).`);
  }
  lines.push("");

  /* Declared agents ───────────────────────────────────────────────── */
  lines.push("## Declared agents");
  lines.push("");
  if (snapshot.agents.length === 0) {
    lines.push("_No agents declared in `settings.agents[]`._");
    if (snapshot.runtime === "bus") {
      lines.push("");
      lines.push("> ⚠ Bus runtime requires at least one declared agent. Without one, the");
      lines.push("> daemon mounts the bus but spawns no `claude` processes — any prompt");
      lines.push("> publishes to the bus with no consumer and sits pending forever.");
    }
  } else {
    for (const a of snapshot.agents) {
      const fields: string[] = [];
      if (a.permissionMode) fields.push(`permission_mode \`${a.permissionMode}\``);
      if (a.cwd) fields.push(`cwd \`${a.cwd}\``);
      if (a.systemPromptFile) fields.push(`system prompt \`${a.systemPromptFile}\``);
      if (a.memoryFile) fields.push(`memory \`${a.memoryFile}\``);
      const tail = fields.length > 0 ? ` — ${fields.join(" — ")}` : "";
      lines.push(`- **\`${a.id}\`**${tail}`);
    }
  }
  lines.push("");

  /* Scheduled jobs ────────────────────────────────────────────────── */
  lines.push("## Scheduled jobs");
  lines.push("");
  if (snapshot.jobs.length === 0) {
    lines.push("_No jobs found under `agents/<name>/jobs/`._");
  } else {
    // Group by agent for readability.
    const byAgent = new Map<string, ArchitectureSnapshotJob[]>();
    for (const j of snapshot.jobs) {
      const list = byAgent.get(j.agent) ?? [];
      list.push(j);
      byAgent.set(j.agent, list);
    }
    const sortedAgents = Array.from(byAgent.keys()).sort();
    for (const agent of sortedAgents) {
      lines.push(`### \`${agent}\``);
      const jobs = byAgent.get(agent)!;
      for (const j of jobs) {
        const sched = j.schedule ? ` — \`${j.schedule}\`` : "";
        const disabled = j.enabled ? "" : " — _disabled_";
        lines.push(`- \`${j.label}\`${sched}${disabled}`);
      }
      lines.push("");
    }
  }

  /* Adapters ──────────────────────────────────────────────────────── */
  lines.push("## Adapters mounted");
  lines.push("");
  if (snapshot.adapters.length === 0) {
    lines.push("_No adapters mounted._");
  } else {
    for (const a of snapshot.adapters) {
      lines.push(`- **${a.name}**${a.detail ? ` — ${a.detail}` : ""}`);
    }
  }
  lines.push("");

  /* Diagnostic playbook ───────────────────────────────────────────── */
  lines.push("## Diagnostic playbook (when something goes quiet)");
  lines.push("");
  lines.push("1. Check `runtime` in `settings.json`. Confirm whether bus or pty.");
  lines.push("2. Compare `agents/<name>/` dirs to `settings.agents[]`. If any on-disk");
  lines.push("   agent isn't declared, that's the issue — prompts publish but no");
  lines.push("   process consumes them.");
  lines.push("3. Grep the event log for `agent_id` prompt vs response counts:");
  lines.push("   ```");
  lines.push(
    `   grep '"agent_id":"<name>"' .claude/claudeclaw/event-log/event-log-<date>*.jsonl \\\\`,
  );
  lines.push("     | jq '.payload.topic' | sort | uniq -c");
  lines.push("   ```");
  lines.push("   Prompts firing with zero responses → agent isn't subscribed.");
  lines.push("4. **Do not guess at PTY timeouts or terminal parsing.** The bus runtime");
  lines.push("   never parses stdout; the pty runtime is `claude -p` subprocesses, not a");
  lines.push("   PTY. Always re-read this file before diagnosing.");
  lines.push("");

  return lines.join("\n");
}

/* ───────────────────────────────────────────────────────────────────── */
/* I/O                                                                   */
/* ───────────────────────────────────────────────────────────────────── */

/**
 * Atomic write: render the doc, write to `<path>.tmp-<random>`, rename to
 * `<path>`. Rename is atomic on POSIX so an in-flight reader (Claude) never
 * sees a partially-written file.
 *
 * Returns the rendered string so callers can also log/assert on the
 * content if useful.
 */
export function writeArchitectureDoc(snapshot: ArchitectureSnapshot, path: string): string {
  const content = renderArchitectureDoc(snapshot);
  const tmpPath = `${path}.tmp-${process.pid}-${Date.now()}`;
  try {
    writeFileSync(tmpPath, content, { encoding: "utf8", mode: 0o644 });
    renameSync(tmpPath, path);
  } catch (err) {
    // Best-effort cleanup of the tmp file so a failed write doesn't leak.
    try {
      unlinkSync(tmpPath);
    } catch {
      /* ok — tmp may not have been created */
    }
    throw err;
  }
  return content;
}

/**
 * Conventional path for the doc. Project root, alongside `CLAUDE.md`. We
 * deliberately don't put it under `.claude/` because Claude treats
 * project-root markdown as bootstrap context.
 */
export function defaultArchitectureDocPath(projectRoot: string): string {
  return join(projectRoot, "CCPLUS_ARCHITECTURE.md");
}
